#define SerialPort ConnectorUsb
#define IOConnector ConnectorCOM0
#define Converyor ConnectorM0
#define Ejection_Converyor ConnectorM1
#define SENSOR_PIN ConnectorDI6
#define IM_SENSOR ConnectorDI8

#define MAX_CUP_COUNT 20
#define EJECTION_OUT_ON_CONVERYOR 2
#define EJECTION_CONVEYOR_MOVE_AMOUNT 10000

#define CONVE_MAX_SPEED 20000
#define CONVE_MIN_SPEED 0
#define CONVE_INCREMENT 1000

#define CUP_UPWORD CLEARCORE_PIN_CCIOA0
#define CUP_PUSHER CLEARCORE_PIN_CCIOA1
#define CUP_DROO CLEARCORE_PIN_CCIOA2
#define CUP_LIFTER CLEARCORE_PIN_CCIOA3
#define CUP_GRABBER CLEARCORE_PIN_CCIOB0

#define CUP_PUSHER_TO_CONVEYOR CLEARCORE_PIN_CCIOC1
#define CUP_PUSHER_TO_CONVEYOR_02 CLEARCORE_PIN_CCIOC3
#define CUP_PUSHER_TO_CONVEYOR_03 CLEARCORE_PIN_CCIOC2
#define PROCESS_SELECTOR CLEARCORE_PIN_CCIOB4


#define CONVERYOR_LIFTER CLEARCORE_PIN_CCIOA4
#define SUCTIONRIGHT CLEARCORE_PIN_CCIOA5
#define SUCTIONLEFT CLEARCORE_PIN_CCIOA6
#define SUCTIONBOTTOM CLEARCORE_PIN_CCIOA7
#define ROTATERIGHT CLEARCORE_PIN_CCIOB5
#define BOTTOMLIFT CLEARCORE_PIN_CCIOB6
#define ROTATELEFT CLEARCORE_PIN_CCIOB7

#define ERROR_EJECTOR ConnectorIO4

#define VAUUM_EJECTOR ConnectorA9

// A0 CUP UP SOLONOID 
// A1 EJECTOR 
// A2 CUP EJECTOR DROO
// 
